
export const ERROR_CODES = {
    INVALID_TOKEN: "INALID_TOKEN",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    VALIDAITON_ERROR: "VALIDATION_ERROR",
    COMPETITION_NOT_FOUND_ERROR: "COMPETITION_NOT_FOUND_ERROR",
    USER_NOT_FOUND_ERROR: "USER_NOT_FOUND_ERROR",
    MISSING_PARAMETERS: "MISSING_PARAMETERS",
    COMPETITION_NOT_ACTIVE: "COMPETITION_NOT_ACTIVE"
};